namespace Jalium.UI.Media;

/// <summary>
/// Contains static predefined SolidColorBrush objects for all standard named colors.
/// </summary>
public static class Brushes
{
    private static SolidColorBrush? _aliceBlue;
    private static SolidColorBrush? _antiqueWhite;
    private static SolidColorBrush? _aqua;
    private static SolidColorBrush? _aquamarine;
    private static SolidColorBrush? _azure;
    private static SolidColorBrush? _beige;
    private static SolidColorBrush? _bisque;
    private static SolidColorBrush? _black;
    private static SolidColorBrush? _blanchedAlmond;
    private static SolidColorBrush? _blue;
    private static SolidColorBrush? _blueViolet;
    private static SolidColorBrush? _brown;
    private static SolidColorBrush? _burlyWood;
    private static SolidColorBrush? _cadetBlue;
    private static SolidColorBrush? _chartreuse;
    private static SolidColorBrush? _chocolate;
    private static SolidColorBrush? _coral;
    private static SolidColorBrush? _cornflowerBlue;
    private static SolidColorBrush? _cornsilk;
    private static SolidColorBrush? _crimson;
    private static SolidColorBrush? _cyan;
    private static SolidColorBrush? _darkBlue;
    private static SolidColorBrush? _darkCyan;
    private static SolidColorBrush? _darkGoldenrod;
    private static SolidColorBrush? _darkGray;
    private static SolidColorBrush? _darkGreen;
    private static SolidColorBrush? _darkKhaki;
    private static SolidColorBrush? _darkMagenta;
    private static SolidColorBrush? _darkOliveGreen;
    private static SolidColorBrush? _darkOrange;
    private static SolidColorBrush? _darkOrchid;
    private static SolidColorBrush? _darkRed;
    private static SolidColorBrush? _darkSalmon;
    private static SolidColorBrush? _darkSeaGreen;
    private static SolidColorBrush? _darkSlateBlue;
    private static SolidColorBrush? _darkSlateGray;
    private static SolidColorBrush? _darkTurquoise;
    private static SolidColorBrush? _darkViolet;
    private static SolidColorBrush? _deepPink;
    private static SolidColorBrush? _deepSkyBlue;
    private static SolidColorBrush? _dimGray;
    private static SolidColorBrush? _dodgerBlue;
    private static SolidColorBrush? _firebrick;
    private static SolidColorBrush? _floralWhite;
    private static SolidColorBrush? _forestGreen;
    private static SolidColorBrush? _fuchsia;
    private static SolidColorBrush? _gainsboro;
    private static SolidColorBrush? _ghostWhite;
    private static SolidColorBrush? _gold;
    private static SolidColorBrush? _goldenrod;
    private static SolidColorBrush? _gray;
    private static SolidColorBrush? _green;
    private static SolidColorBrush? _greenYellow;
    private static SolidColorBrush? _honeydew;
    private static SolidColorBrush? _hotPink;
    private static SolidColorBrush? _indianRed;
    private static SolidColorBrush? _indigo;
    private static SolidColorBrush? _ivory;
    private static SolidColorBrush? _khaki;
    private static SolidColorBrush? _lavender;
    private static SolidColorBrush? _lavenderBlush;
    private static SolidColorBrush? _lawnGreen;
    private static SolidColorBrush? _lemonChiffon;
    private static SolidColorBrush? _lightBlue;
    private static SolidColorBrush? _lightCoral;
    private static SolidColorBrush? _lightCyan;
    private static SolidColorBrush? _lightGoldenrodYellow;
    private static SolidColorBrush? _lightGray;
    private static SolidColorBrush? _lightGreen;
    private static SolidColorBrush? _lightPink;
    private static SolidColorBrush? _lightSalmon;
    private static SolidColorBrush? _lightSeaGreen;
    private static SolidColorBrush? _lightSkyBlue;
    private static SolidColorBrush? _lightSlateGray;
    private static SolidColorBrush? _lightSteelBlue;
    private static SolidColorBrush? _lightYellow;
    private static SolidColorBrush? _lime;
    private static SolidColorBrush? _limeGreen;
    private static SolidColorBrush? _linen;
    private static SolidColorBrush? _magenta;
    private static SolidColorBrush? _maroon;
    private static SolidColorBrush? _mediumAquamarine;
    private static SolidColorBrush? _mediumBlue;
    private static SolidColorBrush? _mediumOrchid;
    private static SolidColorBrush? _mediumPurple;
    private static SolidColorBrush? _mediumSeaGreen;
    private static SolidColorBrush? _mediumSlateBlue;
    private static SolidColorBrush? _mediumSpringGreen;
    private static SolidColorBrush? _mediumTurquoise;
    private static SolidColorBrush? _mediumVioletRed;
    private static SolidColorBrush? _midnightBlue;
    private static SolidColorBrush? _mintCream;
    private static SolidColorBrush? _mistyRose;
    private static SolidColorBrush? _moccasin;
    private static SolidColorBrush? _navajoWhite;
    private static SolidColorBrush? _navy;
    private static SolidColorBrush? _oldLace;
    private static SolidColorBrush? _olive;
    private static SolidColorBrush? _oliveDrab;
    private static SolidColorBrush? _orange;
    private static SolidColorBrush? _orangeRed;
    private static SolidColorBrush? _orchid;
    private static SolidColorBrush? _paleGoldenrod;
    private static SolidColorBrush? _paleGreen;
    private static SolidColorBrush? _paleTurquoise;
    private static SolidColorBrush? _paleVioletRed;
    private static SolidColorBrush? _papayaWhip;
    private static SolidColorBrush? _peachPuff;
    private static SolidColorBrush? _peru;
    private static SolidColorBrush? _pink;
    private static SolidColorBrush? _plum;
    private static SolidColorBrush? _powderBlue;
    private static SolidColorBrush? _purple;
    private static SolidColorBrush? _red;
    private static SolidColorBrush? _rosyBrown;
    private static SolidColorBrush? _royalBlue;
    private static SolidColorBrush? _saddleBrown;
    private static SolidColorBrush? _salmon;
    private static SolidColorBrush? _sandyBrown;
    private static SolidColorBrush? _seaGreen;
    private static SolidColorBrush? _seaShell;
    private static SolidColorBrush? _sienna;
    private static SolidColorBrush? _silver;
    private static SolidColorBrush? _skyBlue;
    private static SolidColorBrush? _slateBlue;
    private static SolidColorBrush? _slateGray;
    private static SolidColorBrush? _snow;
    private static SolidColorBrush? _springGreen;
    private static SolidColorBrush? _steelBlue;
    private static SolidColorBrush? _tan;
    private static SolidColorBrush? _teal;
    private static SolidColorBrush? _thistle;
    private static SolidColorBrush? _tomato;
    private static SolidColorBrush? _transparent;
    private static SolidColorBrush? _turquoise;
    private static SolidColorBrush? _violet;
    private static SolidColorBrush? _wheat;
    private static SolidColorBrush? _white;
    private static SolidColorBrush? _whiteSmoke;
    private static SolidColorBrush? _yellow;
    private static SolidColorBrush? _yellowGreen;

    public static SolidColorBrush AliceBlue => _aliceBlue ??= new SolidColorBrush(Colors.AliceBlue);
    public static SolidColorBrush AntiqueWhite => _antiqueWhite ??= new SolidColorBrush(Colors.AntiqueWhite);
    public static SolidColorBrush Aqua => _aqua ??= new SolidColorBrush(Colors.Aqua);
    public static SolidColorBrush Aquamarine => _aquamarine ??= new SolidColorBrush(Colors.Aquamarine);
    public static SolidColorBrush Azure => _azure ??= new SolidColorBrush(Colors.Azure);
    public static SolidColorBrush Beige => _beige ??= new SolidColorBrush(Colors.Beige);
    public static SolidColorBrush Bisque => _bisque ??= new SolidColorBrush(Colors.Bisque);
    public static SolidColorBrush Black => _black ??= new SolidColorBrush(Colors.Black);
    public static SolidColorBrush BlanchedAlmond => _blanchedAlmond ??= new SolidColorBrush(Colors.BlanchedAlmond);
    public static SolidColorBrush Blue => _blue ??= new SolidColorBrush(Colors.Blue);
    public static SolidColorBrush BlueViolet => _blueViolet ??= new SolidColorBrush(Colors.BlueViolet);
    public static SolidColorBrush Brown => _brown ??= new SolidColorBrush(Colors.Brown);
    public static SolidColorBrush BurlyWood => _burlyWood ??= new SolidColorBrush(Colors.BurlyWood);
    public static SolidColorBrush CadetBlue => _cadetBlue ??= new SolidColorBrush(Colors.CadetBlue);
    public static SolidColorBrush Chartreuse => _chartreuse ??= new SolidColorBrush(Colors.Chartreuse);
    public static SolidColorBrush Chocolate => _chocolate ??= new SolidColorBrush(Colors.Chocolate);
    public static SolidColorBrush Coral => _coral ??= new SolidColorBrush(Colors.Coral);
    public static SolidColorBrush CornflowerBlue => _cornflowerBlue ??= new SolidColorBrush(Colors.CornflowerBlue);
    public static SolidColorBrush Cornsilk => _cornsilk ??= new SolidColorBrush(Colors.Cornsilk);
    public static SolidColorBrush Crimson => _crimson ??= new SolidColorBrush(Colors.Crimson);
    public static SolidColorBrush Cyan => _cyan ??= new SolidColorBrush(Colors.Cyan);
    public static SolidColorBrush DarkBlue => _darkBlue ??= new SolidColorBrush(Colors.DarkBlue);
    public static SolidColorBrush DarkCyan => _darkCyan ??= new SolidColorBrush(Colors.DarkCyan);
    public static SolidColorBrush DarkGoldenrod => _darkGoldenrod ??= new SolidColorBrush(Colors.DarkGoldenrod);
    public static SolidColorBrush DarkGray => _darkGray ??= new SolidColorBrush(Colors.DarkGray);
    public static SolidColorBrush DarkGreen => _darkGreen ??= new SolidColorBrush(Colors.DarkGreen);
    public static SolidColorBrush DarkKhaki => _darkKhaki ??= new SolidColorBrush(Colors.DarkKhaki);
    public static SolidColorBrush DarkMagenta => _darkMagenta ??= new SolidColorBrush(Colors.DarkMagenta);
    public static SolidColorBrush DarkOliveGreen => _darkOliveGreen ??= new SolidColorBrush(Colors.DarkOliveGreen);
    public static SolidColorBrush DarkOrange => _darkOrange ??= new SolidColorBrush(Colors.DarkOrange);
    public static SolidColorBrush DarkOrchid => _darkOrchid ??= new SolidColorBrush(Colors.DarkOrchid);
    public static SolidColorBrush DarkRed => _darkRed ??= new SolidColorBrush(Colors.DarkRed);
    public static SolidColorBrush DarkSalmon => _darkSalmon ??= new SolidColorBrush(Colors.DarkSalmon);
    public static SolidColorBrush DarkSeaGreen => _darkSeaGreen ??= new SolidColorBrush(Colors.DarkSeaGreen);
    public static SolidColorBrush DarkSlateBlue => _darkSlateBlue ??= new SolidColorBrush(Colors.DarkSlateBlue);
    public static SolidColorBrush DarkSlateGray => _darkSlateGray ??= new SolidColorBrush(Colors.DarkSlateGray);
    public static SolidColorBrush DarkTurquoise => _darkTurquoise ??= new SolidColorBrush(Colors.DarkTurquoise);
    public static SolidColorBrush DarkViolet => _darkViolet ??= new SolidColorBrush(Colors.DarkViolet);
    public static SolidColorBrush DeepPink => _deepPink ??= new SolidColorBrush(Colors.DeepPink);
    public static SolidColorBrush DeepSkyBlue => _deepSkyBlue ??= new SolidColorBrush(Colors.DeepSkyBlue);
    public static SolidColorBrush DimGray => _dimGray ??= new SolidColorBrush(Colors.DimGray);
    public static SolidColorBrush DodgerBlue => _dodgerBlue ??= new SolidColorBrush(Colors.DodgerBlue);
    public static SolidColorBrush Firebrick => _firebrick ??= new SolidColorBrush(Colors.Firebrick);
    public static SolidColorBrush FloralWhite => _floralWhite ??= new SolidColorBrush(Colors.FloralWhite);
    public static SolidColorBrush ForestGreen => _forestGreen ??= new SolidColorBrush(Colors.ForestGreen);
    public static SolidColorBrush Fuchsia => _fuchsia ??= new SolidColorBrush(Colors.Fuchsia);
    public static SolidColorBrush Gainsboro => _gainsboro ??= new SolidColorBrush(Colors.Gainsboro);
    public static SolidColorBrush GhostWhite => _ghostWhite ??= new SolidColorBrush(Colors.GhostWhite);
    public static SolidColorBrush Gold => _gold ??= new SolidColorBrush(Colors.Gold);
    public static SolidColorBrush Goldenrod => _goldenrod ??= new SolidColorBrush(Colors.Goldenrod);
    public static SolidColorBrush Gray => _gray ??= new SolidColorBrush(Colors.Gray);
    public static SolidColorBrush Green => _green ??= new SolidColorBrush(Colors.Green);
    public static SolidColorBrush GreenYellow => _greenYellow ??= new SolidColorBrush(Colors.GreenYellow);
    public static SolidColorBrush Honeydew => _honeydew ??= new SolidColorBrush(Colors.Honeydew);
    public static SolidColorBrush HotPink => _hotPink ??= new SolidColorBrush(Colors.HotPink);
    public static SolidColorBrush IndianRed => _indianRed ??= new SolidColorBrush(Colors.IndianRed);
    public static SolidColorBrush Indigo => _indigo ??= new SolidColorBrush(Colors.Indigo);
    public static SolidColorBrush Ivory => _ivory ??= new SolidColorBrush(Colors.Ivory);
    public static SolidColorBrush Khaki => _khaki ??= new SolidColorBrush(Colors.Khaki);
    public static SolidColorBrush Lavender => _lavender ??= new SolidColorBrush(Colors.Lavender);
    public static SolidColorBrush LavenderBlush => _lavenderBlush ??= new SolidColorBrush(Colors.LavenderBlush);
    public static SolidColorBrush LawnGreen => _lawnGreen ??= new SolidColorBrush(Colors.LawnGreen);
    public static SolidColorBrush LemonChiffon => _lemonChiffon ??= new SolidColorBrush(Colors.LemonChiffon);
    public static SolidColorBrush LightBlue => _lightBlue ??= new SolidColorBrush(Colors.LightBlue);
    public static SolidColorBrush LightCoral => _lightCoral ??= new SolidColorBrush(Colors.LightCoral);
    public static SolidColorBrush LightCyan => _lightCyan ??= new SolidColorBrush(Colors.LightCyan);
    public static SolidColorBrush LightGoldenrodYellow => _lightGoldenrodYellow ??= new SolidColorBrush(Colors.LightGoldenrodYellow);
    public static SolidColorBrush LightGray => _lightGray ??= new SolidColorBrush(Colors.LightGray);
    public static SolidColorBrush LightGreen => _lightGreen ??= new SolidColorBrush(Colors.LightGreen);
    public static SolidColorBrush LightPink => _lightPink ??= new SolidColorBrush(Colors.LightPink);
    public static SolidColorBrush LightSalmon => _lightSalmon ??= new SolidColorBrush(Colors.LightSalmon);
    public static SolidColorBrush LightSeaGreen => _lightSeaGreen ??= new SolidColorBrush(Colors.LightSeaGreen);
    public static SolidColorBrush LightSkyBlue => _lightSkyBlue ??= new SolidColorBrush(Colors.LightSkyBlue);
    public static SolidColorBrush LightSlateGray => _lightSlateGray ??= new SolidColorBrush(Colors.LightSlateGray);
    public static SolidColorBrush LightSteelBlue => _lightSteelBlue ??= new SolidColorBrush(Colors.LightSteelBlue);
    public static SolidColorBrush LightYellow => _lightYellow ??= new SolidColorBrush(Colors.LightYellow);
    public static SolidColorBrush Lime => _lime ??= new SolidColorBrush(Colors.Lime);
    public static SolidColorBrush LimeGreen => _limeGreen ??= new SolidColorBrush(Colors.LimeGreen);
    public static SolidColorBrush Linen => _linen ??= new SolidColorBrush(Colors.Linen);
    public static SolidColorBrush Magenta => _magenta ??= new SolidColorBrush(Colors.Magenta);
    public static SolidColorBrush Maroon => _maroon ??= new SolidColorBrush(Colors.Maroon);
    public static SolidColorBrush MediumAquamarine => _mediumAquamarine ??= new SolidColorBrush(Colors.MediumAquamarine);
    public static SolidColorBrush MediumBlue => _mediumBlue ??= new SolidColorBrush(Colors.MediumBlue);
    public static SolidColorBrush MediumOrchid => _mediumOrchid ??= new SolidColorBrush(Colors.MediumOrchid);
    public static SolidColorBrush MediumPurple => _mediumPurple ??= new SolidColorBrush(Colors.MediumPurple);
    public static SolidColorBrush MediumSeaGreen => _mediumSeaGreen ??= new SolidColorBrush(Colors.MediumSeaGreen);
    public static SolidColorBrush MediumSlateBlue => _mediumSlateBlue ??= new SolidColorBrush(Colors.MediumSlateBlue);
    public static SolidColorBrush MediumSpringGreen => _mediumSpringGreen ??= new SolidColorBrush(Colors.MediumSpringGreen);
    public static SolidColorBrush MediumTurquoise => _mediumTurquoise ??= new SolidColorBrush(Colors.MediumTurquoise);
    public static SolidColorBrush MediumVioletRed => _mediumVioletRed ??= new SolidColorBrush(Colors.MediumVioletRed);
    public static SolidColorBrush MidnightBlue => _midnightBlue ??= new SolidColorBrush(Colors.MidnightBlue);
    public static SolidColorBrush MintCream => _mintCream ??= new SolidColorBrush(Colors.MintCream);
    public static SolidColorBrush MistyRose => _mistyRose ??= new SolidColorBrush(Colors.MistyRose);
    public static SolidColorBrush Moccasin => _moccasin ??= new SolidColorBrush(Colors.Moccasin);
    public static SolidColorBrush NavajoWhite => _navajoWhite ??= new SolidColorBrush(Colors.NavajoWhite);
    public static SolidColorBrush Navy => _navy ??= new SolidColorBrush(Colors.Navy);
    public static SolidColorBrush OldLace => _oldLace ??= new SolidColorBrush(Colors.OldLace);
    public static SolidColorBrush Olive => _olive ??= new SolidColorBrush(Colors.Olive);
    public static SolidColorBrush OliveDrab => _oliveDrab ??= new SolidColorBrush(Colors.OliveDrab);
    public static SolidColorBrush Orange => _orange ??= new SolidColorBrush(Colors.Orange);
    public static SolidColorBrush OrangeRed => _orangeRed ??= new SolidColorBrush(Colors.OrangeRed);
    public static SolidColorBrush Orchid => _orchid ??= new SolidColorBrush(Colors.Orchid);
    public static SolidColorBrush PaleGoldenrod => _paleGoldenrod ??= new SolidColorBrush(Colors.PaleGoldenrod);
    public static SolidColorBrush PaleGreen => _paleGreen ??= new SolidColorBrush(Colors.PaleGreen);
    public static SolidColorBrush PaleTurquoise => _paleTurquoise ??= new SolidColorBrush(Colors.PaleTurquoise);
    public static SolidColorBrush PaleVioletRed => _paleVioletRed ??= new SolidColorBrush(Colors.PaleVioletRed);
    public static SolidColorBrush PapayaWhip => _papayaWhip ??= new SolidColorBrush(Colors.PapayaWhip);
    public static SolidColorBrush PeachPuff => _peachPuff ??= new SolidColorBrush(Colors.PeachPuff);
    public static SolidColorBrush Peru => _peru ??= new SolidColorBrush(Colors.Peru);
    public static SolidColorBrush Pink => _pink ??= new SolidColorBrush(Colors.Pink);
    public static SolidColorBrush Plum => _plum ??= new SolidColorBrush(Colors.Plum);
    public static SolidColorBrush PowderBlue => _powderBlue ??= new SolidColorBrush(Colors.PowderBlue);
    public static SolidColorBrush Purple => _purple ??= new SolidColorBrush(Colors.Purple);
    public static SolidColorBrush Red => _red ??= new SolidColorBrush(Colors.Red);
    public static SolidColorBrush RosyBrown => _rosyBrown ??= new SolidColorBrush(Colors.RosyBrown);
    public static SolidColorBrush RoyalBlue => _royalBlue ??= new SolidColorBrush(Colors.RoyalBlue);
    public static SolidColorBrush SaddleBrown => _saddleBrown ??= new SolidColorBrush(Colors.SaddleBrown);
    public static SolidColorBrush Salmon => _salmon ??= new SolidColorBrush(Colors.Salmon);
    public static SolidColorBrush SandyBrown => _sandyBrown ??= new SolidColorBrush(Colors.SandyBrown);
    public static SolidColorBrush SeaGreen => _seaGreen ??= new SolidColorBrush(Colors.SeaGreen);
    public static SolidColorBrush SeaShell => _seaShell ??= new SolidColorBrush(Colors.SeaShell);
    public static SolidColorBrush Sienna => _sienna ??= new SolidColorBrush(Colors.Sienna);
    public static SolidColorBrush Silver => _silver ??= new SolidColorBrush(Colors.Silver);
    public static SolidColorBrush SkyBlue => _skyBlue ??= new SolidColorBrush(Colors.SkyBlue);
    public static SolidColorBrush SlateBlue => _slateBlue ??= new SolidColorBrush(Colors.SlateBlue);
    public static SolidColorBrush SlateGray => _slateGray ??= new SolidColorBrush(Colors.SlateGray);
    public static SolidColorBrush Snow => _snow ??= new SolidColorBrush(Colors.Snow);
    public static SolidColorBrush SpringGreen => _springGreen ??= new SolidColorBrush(Colors.SpringGreen);
    public static SolidColorBrush SteelBlue => _steelBlue ??= new SolidColorBrush(Colors.SteelBlue);
    public static SolidColorBrush Tan => _tan ??= new SolidColorBrush(Colors.Tan);
    public static SolidColorBrush Teal => _teal ??= new SolidColorBrush(Colors.Teal);
    public static SolidColorBrush Thistle => _thistle ??= new SolidColorBrush(Colors.Thistle);
    public static SolidColorBrush Tomato => _tomato ??= new SolidColorBrush(Colors.Tomato);
    public static SolidColorBrush Transparent => _transparent ??= new SolidColorBrush(Colors.Transparent);
    public static SolidColorBrush Turquoise => _turquoise ??= new SolidColorBrush(Colors.Turquoise);
    public static SolidColorBrush Violet => _violet ??= new SolidColorBrush(Colors.Violet);
    public static SolidColorBrush Wheat => _wheat ??= new SolidColorBrush(Colors.Wheat);
    public static SolidColorBrush White => _white ??= new SolidColorBrush(Colors.White);
    public static SolidColorBrush WhiteSmoke => _whiteSmoke ??= new SolidColorBrush(Colors.WhiteSmoke);
    public static SolidColorBrush Yellow => _yellow ??= new SolidColorBrush(Colors.Yellow);
    public static SolidColorBrush YellowGreen => _yellowGreen ??= new SolidColorBrush(Colors.YellowGreen);
}
