using System.Collections.Immutable;
using System.Text;
using System.Xml;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Jalium.UI.Xaml.SourceGenerator;

/// <summary>
/// Source generator that generates InitializeComponent methods for JALXAML files.
/// Generates code that loads from embedded JALXAML resources at runtime.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class JalxamlSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Get all .jalxaml files
        var jalxamlFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".jalxaml", StringComparison.OrdinalIgnoreCase));

        // Get compilation info for assembly name
        var compilationAndFiles = context.CompilationProvider
            .Combine(jalxamlFiles.Collect());

        // Generate source for each JALXAML file
        context.RegisterSourceOutput(compilationAndFiles, (spc, source) =>
        {
            var (compilation, jalxamlFileList) = source;
            var assemblyName = compilation.AssemblyName ?? "Unknown";

            foreach (var file in jalxamlFileList)
            {
                GenerateForJalxaml(spc, file, assemblyName);
            }
        });
    }

    private void GenerateForJalxaml(SourceProductionContext context, AdditionalText file, string assemblyName)
    {
        var content = file.GetText(context.CancellationToken)?.ToString();
        if (string.IsNullOrEmpty(content))
            return;

        try
        {
            var parseResult = JalxamlParser.Parse(content!, file.Path);
            if (parseResult?.ClassName == null || string.IsNullOrEmpty(parseResult.ClassName))
                return;

            var className = parseResult.ClassName;
            var generatedCode = GenerateCode(parseResult, assemblyName);
            var fileName = $"{className.Replace(".", "_")}.g.cs";

            context.AddSource(fileName, SourceText.From(generatedCode, Encoding.UTF8));
        }
        catch (Exception ex)
        {
            // Report diagnostic for parse errors
            var diagnostic = Diagnostic.Create(
                new DiagnosticDescriptor(
                    "JALXAML001",
                    "JALXAML Parse Error",
                    "Failed to parse JALXAML file '{0}': {1}",
                    "Jalium.UI.Xaml",
                    DiagnosticSeverity.Warning,
                    isEnabledByDefault: true),
                Location.None,
                file.Path,
                ex.Message);
            context.ReportDiagnostic(diagnostic);
        }
    }

    private string GenerateCode(JalxamlParseResult result, string assemblyName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0649 // Field is never assigned - wired up by XAML loader at runtime");
        sb.AppendLine();
        sb.AppendLine("using Jalium.UI.Controls;");
        sb.AppendLine("using Jalium.UI.Controls.Primitives;");
        sb.AppendLine("using Jalium.UI.Markup;");
        sb.AppendLine();

        // Extract namespace and class name
        var lastDot = result.ClassName!.LastIndexOf('.');
        var namespaceName = lastDot > 0 ? result.ClassName.Substring(0, lastDot) : null;
        var className = lastDot > 0 ? result.ClassName.Substring(lastDot + 1) : result.ClassName;

        if (namespaceName != null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");

        // Generate fields for named elements
        foreach (var element in result.NamedElements)
        {
            sb.AppendLine($"    private {element.TypeName}? {element.Name};");
        }

        if (result.NamedElements.Count > 0)
        {
            sb.AppendLine();
        }

        // Generate InitializeComponent method
        // Use runtime XAML parsing to create control instances and wire up named elements
        // The .jalxaml file is embedded as a resource using the full x:Class name
        // Example: x:Class="Jalium.UI.Gallery.Views.HomePage" -> "Jalium.UI.Gallery.Views.HomePage.jalxaml"
        var resourceName = $"{result.ClassName}.jalxaml";

        sb.AppendLine("    private void InitializeComponent()");
        sb.AppendLine("    {");

        if (result.NamedElements.Count > 0)
        {
            // AOT-safe: Use the overload that returns named elements as a dictionary
            // instead of wiring via reflection (which fails when private field metadata is trimmed)
            sb.AppendLine($"        var _namedElements = new System.Collections.Generic.Dictionary<string, object>();");
            sb.AppendLine($"        XamlReader.LoadComponent(this, \"{resourceName}\", _namedElements);");

            // Generate explicit wiring for each named element (no reflection needed)
            foreach (var element in result.NamedElements)
            {
                sb.AppendLine($"        if (_namedElements.TryGetValue(\"{element.Name}\", out var _{element.Name}_val))");
                sb.AppendLine($"            {element.Name} = _{element.Name}_val as {element.TypeName};");
            }
        }
        else
        {
            // No named elements - use the simple overload
            sb.AppendLine($"        XamlReader.LoadComponent(this, \"{resourceName}\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

/// <summary>
/// Represents a parsed JALXAML file.
/// </summary>
public sealed class JalxamlParseResult
{
    public string? ClassName { get; set; }
    public string? RootElementType { get; set; }
    public List<NamedElement> NamedElements { get; } = new();
}

/// <summary>
/// Represents a named element (x:Name) in JALXAML.
/// </summary>
public sealed class NamedElement
{
    public string Name { get; set; } = string.Empty;
    public string TypeName { get; set; } = string.Empty;
}
