using System.Collections.Immutable;
using System.Text;
using System.Xml;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Jalium.UI.Xaml.SourceGenerator;

/// <summary>
/// Source generator that generates InitializeComponent methods for JALXAML files.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class JalxamlSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Get all .jalxaml files
        var jalxamlFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".jalxaml", StringComparison.OrdinalIgnoreCase));

        // Get compilation info for assembly name
        var compilationAndFiles = context.CompilationProvider
            .Combine(jalxamlFiles.Collect());

        // Generate source for each JALXAML file
        context.RegisterSourceOutput(compilationAndFiles, (spc, source) =>
        {
            var (compilation, files) = source;
            var assemblyName = compilation.AssemblyName ?? "Unknown";

            foreach (var file in files)
            {
                GenerateForJalxaml(spc, file, assemblyName);
            }
        });
    }

    private void GenerateForJalxaml(SourceProductionContext context, AdditionalText file, string assemblyName)
    {
        var content = file.GetText(context.CancellationToken)?.ToString();
        if (string.IsNullOrEmpty(content))
            return;

        try
        {
            var parseResult = JalxamlParser.Parse(content!, file.Path);
            if (parseResult?.ClassName == null || string.IsNullOrEmpty(parseResult.ClassName))
                return;

            var className = parseResult.ClassName;
            var generatedCode = GenerateCode(parseResult, assemblyName, file.Path);
            var fileName = $"{className.Replace(".", "_")}.g.cs";

            context.AddSource(fileName, SourceText.From(generatedCode, Encoding.UTF8));
        }
        catch (Exception ex)
        {
            // Report diagnostic for parse errors
            var diagnostic = Diagnostic.Create(
                new DiagnosticDescriptor(
                    "JALXAML001",
                    "JALXAML Parse Error",
                    "Failed to parse JALXAML file '{0}': {1}",
                    "Jalium.UI.Xaml",
                    DiagnosticSeverity.Warning,
                    isEnabledByDefault: true),
                Location.None,
                file.Path,
                ex.Message);
            context.ReportDiagnostic(diagnostic);
        }
    }

    private string GenerateCode(JalxamlParseResult result, string assemblyName, string filePath)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0649 // Field is never assigned - wired up by JALXAML loader at runtime");
        sb.AppendLine();
        sb.AppendLine("using Jalium.UI.Controls;");
        sb.AppendLine("using Jalium.UI.Markup;");
        sb.AppendLine();

        // Extract namespace and class name
        var lastDot = result.ClassName!.LastIndexOf('.');
        var namespaceName = lastDot > 0 ? result.ClassName.Substring(0, lastDot) : null;
        var className = lastDot > 0 ? result.ClassName.Substring(lastDot + 1) : result.ClassName;

        if (namespaceName != null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");

        // Generate fields for named elements
        foreach (var element in result.NamedElements)
        {
            sb.AppendLine($"    private {element.TypeName}? {element.Name};");
        }

        if (result.NamedElements.Count > 0)
        {
            sb.AppendLine();
        }

        // Generate InitializeComponent method
        sb.AppendLine("    private void InitializeComponent()");
        sb.AppendLine("    {");

        // Calculate Pack URI from file path
        // Format: /AssemblyName;component/Path/To/File.jalxaml
        var componentPath = CalculateComponentPath(filePath, assemblyName);
        var packUri = $"/{assemblyName};component/{componentPath}";
        sb.AppendLine($"        JalxamlLoader.LoadComponent(this, new System.Uri(\"{packUri}\", System.UriKind.Relative));");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private string CalculateComponentPath(string filePath, string assemblyName)
    {
        // Extract relative path from file path
        // File paths can be like:
        //   d:\Users\...\Jalium.UI.Gallery\Views\ButtonPage.jalxaml
        //   d:\Users\...\Jalium.UI.Gallery\GalleryWindow.jalxaml
        // We need to find the part after the project folder (which typically matches assembly name)

        // Normalize path separators
        var normalizedPath = filePath.Replace('\\', '/');

        // Try to find the assembly name in the path (project folder)
        var assemblyIndex = normalizedPath.LastIndexOf($"/{assemblyName}/", StringComparison.OrdinalIgnoreCase);
        if (assemblyIndex >= 0)
        {
            // Return path after "AssemblyName/"
            var startIndex = assemblyIndex + assemblyName.Length + 2; // +2 for the two '/'
            return normalizedPath.Substring(startIndex);
        }

        // Fallback: try to find just the filename and parent folders
        // Look for common patterns like "samples/ProjectName/" or "src/ProjectName/"
        var segments = normalizedPath.Split('/');

        // Find the segment that matches the assembly name (case-insensitive)
        for (int i = segments.Length - 2; i >= 0; i--)
        {
            if (segments[i].Equals(assemblyName, StringComparison.OrdinalIgnoreCase))
            {
                // Return everything after this segment
                return string.Join("/", segments, i + 1, segments.Length - i - 1);
            }
        }

        // Last fallback: just use the filename
        return Path.GetFileName(filePath);
    }
}

/// <summary>
/// Represents a parsed JALXAML file.
/// </summary>
public class JalxamlParseResult
{
    public string? ClassName { get; set; }
    public string? RootElementType { get; set; }
    public List<NamedElement> NamedElements { get; } = new();
}

/// <summary>
/// Represents a named element (x:Name) in JALXAML.
/// </summary>
public class NamedElement
{
    public string Name { get; set; } = string.Empty;
    public string TypeName { get; set; } = string.Empty;
}
