using Jalium.UI.Controls;

namespace Jalium.UI.Gallery.Views;

/// <summary>
/// Code-behind for ButtonPage.jalxaml demonstrating interactive button functionality.
/// Fields (CounterButton, CounterText) and InitializeComponent() are generated by source generator.
/// </summary>
public partial class ButtonPage : Page
{
    private int _counter;

    public ButtonPage()
    {
        InitializeComponent();

        // Set up event handlers after component initialization
        if (CounterButton != null)
        {
            CounterButton.Click += OnCounterButtonClick;
        }
    }

    private void OnCounterButtonClick(object? sender, EventArgs e)
    {
        _counter++;
        if (CounterText != null)
        {
            CounterText.Text = $"Count: {_counter}";
        }
    }
}
