// <auto-generated-path>Editor/LanguageServer/Client/JsonRpcConnection.cs</auto-generated-path>
// JSON-RPC 2.0 transport layer for LSP communication over stdin/stdout streams.

using System.Collections.Concurrent;
using System.Text;
using System.Text.Json;
using Jalium.UI.Controls.Editor.LanguageServer.JsonRpc;
using Jalium.UI.Controls.Editor.LanguageServer.Protocol;

namespace Jalium.UI.Controls.Editor.LanguageServer.Client;

/// <summary>
/// Manages a JSON-RPC 2.0 connection over a pair of streams (typically stdin/stdout of a language server process).
/// Handles message framing (Content-Length headers), request/response correlation, and notification dispatch.
/// </summary>
internal sealed class JsonRpcConnection : IAsyncDisposable
{
    private readonly Stream _input;
    private readonly Stream _output;
    private readonly ConcurrentDictionary<long, TaskCompletionSource<JsonElement?>> _pendingRequests = new();
    private readonly JsonSerializerOptions _jsonOptions;
    private long _nextRequestId;
    private Task? _readLoopTask;
    private readonly CancellationTokenSource _cts = new();
    private bool _disposed;

    /// <summary>
    /// Raised when the server sends a notification message.
    /// </summary>
    public event Action<string, JsonElement?>? NotificationReceived;

    /// <summary>
    /// Raised when the server sends a request message (e.g., workspace/applyEdit).
    /// The handler should return a result JsonElement or null.
    /// </summary>
    public event Func<string, JsonElement?, object?, Task<JsonElement?>>? RequestReceived;

    /// <summary>
    /// Raised when the connection encounters a fatal error.
    /// </summary>
    public event Action<Exception>? ConnectionError;

    /// <summary>
    /// Raised when the connection is closed (server process exited or stream closed).
    /// </summary>
    public event Action? ConnectionClosed;

    public JsonRpcConnection(Stream input, Stream output)
    {
        _input = input;
        _output = output;
        _jsonOptions = new JsonSerializerOptions
        {
            DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        };
    }

    /// <summary>
    /// Starts the background read loop to process incoming messages.
    /// </summary>
    public void StartListening()
    {
        if (_readLoopTask != null)
            throw new InvalidOperationException("Already listening.");
        _readLoopTask = Task.Run(() => ReadLoopAsync(_cts.Token));
    }

    /// <summary>
    /// Sends a JSON-RPC request and waits for the response.
    /// </summary>
    public async Task<JsonElement?> SendRequestAsync(string method, object? @params, CancellationToken ct = default)
    {
        var id = Interlocked.Increment(ref _nextRequestId);
        var tcs = new TaskCompletionSource<JsonElement?>(TaskCreationOptions.RunContinuationsAsynchronously);
        _pendingRequests[id] = tcs;

        using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(ct, _cts.Token);
        linkedCts.Token.Register(() =>
        {
            if (_pendingRequests.TryRemove(id, out var removed))
                removed.TrySetCanceled();
        });

        var request = new RequestMessage
        {
            Id = id,
            Method = method,
            Params = SerializeParams(@params),
        };

        await WriteMessageAsync(request, linkedCts.Token).ConfigureAwait(false);

        return await tcs.Task.ConfigureAwait(false);
    }

    /// <summary>
    /// Sends a JSON-RPC request and deserializes the response to the specified type.
    /// </summary>
    public async Task<TResult?> SendRequestAsync<TResult>(string method, object? @params, CancellationToken ct = default)
    {
        var result = await SendRequestAsync(method, @params, ct).ConfigureAwait(false);
        if (result == null || result.Value.ValueKind == JsonValueKind.Null)
            return default;
        return result.Value.Deserialize<TResult>(_jsonOptions);
    }

    /// <summary>
    /// Sends a JSON-RPC notification (no response expected).
    /// </summary>
    public async Task SendNotificationAsync(string method, object? @params, CancellationToken ct = default)
    {
        var notification = new NotificationMessage
        {
            Method = method,
            Params = SerializeParams(@params),
        };
        await WriteMessageAsync(notification, ct).ConfigureAwait(false);
    }

    /// <summary>
    /// Sends a cancellation notification for a pending request.
    /// </summary>
    public Task SendCancelNotificationAsync(long requestId, CancellationToken ct = default)
    {
        return SendNotificationAsync(LspMethods.CancelRequest, new { id = requestId }, ct);
    }

    private JsonElement? SerializeParams(object? @params)
    {
        if (@params == null) return null;
        if (@params is JsonElement je) return je;
        var bytes = JsonSerializer.SerializeToUtf8Bytes(@params, @params.GetType(), _jsonOptions);
        using var doc = JsonDocument.Parse(bytes);
        return doc.RootElement.Clone();
    }

    private async Task WriteMessageAsync(object message, CancellationToken ct)
    {
        var jsonBytes = JsonSerializer.SerializeToUtf8Bytes(message, message.GetType(), _jsonOptions);
        await HeaderParser.WriteMessageAsync(_output, jsonBytes, ct).ConfigureAwait(false);
    }

    private async Task ReadLoopAsync(CancellationToken ct)
    {
        try
        {
            while (!ct.IsCancellationRequested)
            {
                int contentLength = await HeaderParser.ReadContentLengthAsync(_input, ct).ConfigureAwait(false);
                if (contentLength < 0)
                {
                    // EOF — server closed
                    ConnectionClosed?.Invoke();
                    return;
                }

                byte[] body = new byte[contentLength];
                int totalRead = 0;
                while (totalRead < contentLength)
                {
                    int read = await _input.ReadAsync(body, totalRead, contentLength - totalRead, ct).ConfigureAwait(false);
                    if (read == 0)
                    {
                        ConnectionClosed?.Invoke();
                        return;
                    }
                    totalRead += read;
                }

                using var doc = JsonDocument.Parse(body);
                var root = doc.RootElement;

                // Determine message type based on presence of id and method
                bool hasId = root.TryGetProperty("id", out var idElement);
                bool hasMethod = root.TryGetProperty("method", out var methodElement);

                if (hasId && hasMethod)
                {
                    // Server-initiated request
                    await HandleServerRequestAsync(root, idElement, methodElement.GetString()!, ct).ConfigureAwait(false);
                }
                else if (hasId && !hasMethod)
                {
                    // Response to a client request
                    HandleResponse(root, idElement);
                }
                else if (!hasId && hasMethod)
                {
                    // Notification from server
                    HandleNotification(methodElement.GetString()!, root);
                }
            }
        }
        catch (OperationCanceledException) when (ct.IsCancellationRequested)
        {
            // Normal shutdown
        }
        catch (Exception ex)
        {
            ConnectionError?.Invoke(ex);
            CancelAllPending(ex);
        }
    }

    private void HandleResponse(JsonElement root, JsonElement idElement)
    {
        long id = idElement.ValueKind == JsonValueKind.String
            ? long.Parse(idElement.GetString()!)
            : idElement.GetInt64();

        if (!_pendingRequests.TryRemove(id, out var tcs))
            return;

        if (root.TryGetProperty("error", out var errorElement))
        {
            var error = errorElement.Deserialize<ResponseError>(_jsonOptions);
            tcs.TrySetException(new JsonRpcException(
                error?.Code ?? LspErrorCodes.InternalError,
                error?.Message ?? "Unknown error",
                error?.Data));
        }
        else if (root.TryGetProperty("result", out var resultElement))
        {
            tcs.TrySetResult(resultElement.Clone());
        }
        else
        {
            tcs.TrySetResult(null);
        }
    }

    private void HandleNotification(string method, JsonElement root)
    {
        JsonElement? @params = root.TryGetProperty("params", out var p) ? p.Clone() : null;
        NotificationReceived?.Invoke(method, @params);
    }

    private async Task HandleServerRequestAsync(JsonElement root, JsonElement idElement, string method, CancellationToken ct)
    {
        JsonElement? @params = root.TryGetProperty("params", out var p) ? p.Clone() : null;

        JsonElement? result = null;
        ResponseError? error = null;

        try
        {
            if (RequestReceived != null)
            {
                result = await RequestReceived.Invoke(method, @params, idElement.Clone()).ConfigureAwait(false);
            }
            else
            {
                error = new ResponseError
                {
                    Code = LspErrorCodes.MethodNotFound,
                    Message = $"No handler for server request: {method}",
                };
            }
        }
        catch (Exception ex)
        {
            error = new ResponseError
            {
                Code = LspErrorCodes.InternalError,
                Message = ex.Message,
            };
        }

        // Send response back to server
        var response = new ResponseMessage
        {
            Id = idElement.ValueKind == JsonValueKind.String ? idElement.GetString()! : (object)idElement.GetInt64(),
            Result = result,
            Error = error,
        };
        await WriteMessageAsync(response, ct).ConfigureAwait(false);
    }

    private void CancelAllPending(Exception ex)
    {
        foreach (var kvp in _pendingRequests)
        {
            if (_pendingRequests.TryRemove(kvp.Key, out var tcs))
                tcs.TrySetException(ex);
        }
    }

    public async ValueTask DisposeAsync()
    {
        if (_disposed) return;
        _disposed = true;

        _cts.Cancel();

        CancelAllPending(new ObjectDisposedException(nameof(JsonRpcConnection)));

        if (_readLoopTask != null)
        {
            try { await _readLoopTask.ConfigureAwait(false); }
            catch { /* swallow */ }
        }

        _cts.Dispose();
    }
}
