using System.Text;
using Jalium.UI.Gpu;

namespace Jalium.UI.Compiler;

/// <summary>
/// JALXAML 编译器命令行工具
/// Usage: jalxamlc [options] <input.jalxaml> [output.juib]
///
/// Options:
///   -o, --output <path>    指定输出文件路径
///   -d, --output-dir <dir> 指定输出目录
///   -O, --optimize         启用优化（默认）
///   -O0                    禁用优化
///   -g, --debug            生成调试信息
///   -c, --codegen          生成代码隐藏 (.g.cs)
///   -n, --namespace <ns>   指定代码生成的根命名空间
///   -h, --help             显示帮助信息
///   -v, --version          显示版本信息
/// </summary>
internal class Program
{
    private static int Main(string[] args)
    {
        if (args.Length == 0 || args.Contains("-h") || args.Contains("--help"))
        {
            PrintHelp();
            return 0;
        }

        if (args.Contains("-v") || args.Contains("--version"))
        {
            PrintVersion();
            return 0;
        }

        var options = ParseOptions(args);

        if (options.InputFiles.Count == 0)
        {
            Console.Error.WriteLine("错误: 未指定输入文件");
            return 1;
        }

        var hasErrors = false;

        foreach (var inputFile in options.InputFiles)
        {
            if (!File.Exists(inputFile))
            {
                Console.Error.WriteLine($"错误: 文件不存在 - {inputFile}");
                hasErrors = true;
                continue;
            }

            try
            {
                CompileFile(inputFile, options);
                Console.WriteLine($"已编译: {inputFile}");
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"错误: 编译失败 [{inputFile}] - {ex.Message}");
                hasErrors = true;
            }
        }

        return hasErrors ? 1 : 0;
    }

    private static void CompileFile(string inputFile, CompilerCliOptions options)
    {
        // 计算输出路径
        var outputPath = GetOutputPath(inputFile, options);

        // 创建编译器
        var compiler = new UICompiler
        {
            EnableOptimization = options.Optimize,
            GenerateDebugInfo = options.Debug
        };

        // 编译
        compiler.AddSourceFile(inputFile);
        var bundle = compiler.Compile();

        if (bundle == null)
        {
            throw new InvalidOperationException("编译返回空结果");
        }

        // 确保输出目录存在
        var outputDir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(outputDir))
        {
            Directory.CreateDirectory(outputDir);
        }

        // 保存二进制包
        BundleSerializer.Save(bundle, outputPath);

        // 生成代码隐藏文件
        if (options.GenerateCodeBehind)
        {
            GenerateCodeBehind(inputFile, options);
        }
    }

    private static void GenerateCodeBehind(string inputFile, CompilerCliOptions options)
    {
        var parser = new JalxamlParser();
        var document = parser.ParseFile(inputFile);

        if (document == null)
        {
            Console.Error.WriteLine($"警告: 无法解析文件以生成代码隐藏 - {inputFile}");
            return;
        }

        var outputDir = options.OutputDirectory ?? Path.GetDirectoryName(inputFile) ?? ".";
        var fileName = Path.GetFileNameWithoutExtension(inputFile);
        var codePath = Path.Combine(outputDir, fileName + ".g.cs");

        var code = GenerateCode(document, fileName, options.RootNamespace);
        File.WriteAllText(codePath, code);

        Console.WriteLine($"已生成: {codePath}");
    }

    private static string GenerateCode(JalxamlDocument document, string className, string? rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 此代码由 jalxamlc 编译器自动生成");
        sb.AppendLine("// 请勿手动修改此文件");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var ns = document.ClassName?.Contains(".") == true
            ? document.ClassName.Substring(0, document.ClassName.LastIndexOf('.'))
            : rootNamespace;

        var actualClassName = document.ClassName?.Contains(".") == true
            ? document.ClassName.Substring(document.ClassName.LastIndexOf('.') + 1)
            : className;

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {actualClassName}");
        sb.AppendLine("{");

        // 生成命名元素字段
        foreach (var namedElement in document.NamedElements)
        {
            var fieldName = namedElement.Name;
            var typeName = namedElement.TypeName ?? "Jalium.UI.FrameworkElement";
            sb.AppendLine($"    private {typeName} {fieldName} = default!;");
        }

        sb.AppendLine();

        // 生成 InitializeComponent 方法
        sb.AppendLine("    private void InitializeComponent()");
        sb.AppendLine("    {");
        sb.AppendLine($"        // 加载编译后的 JALXAML 资源");
        sb.AppendLine($"        var bundle = Jalium.UI.Gpu.UIRuntime.LoadBundle(\"{actualClassName}.juib\");");
        sb.AppendLine($"        Jalium.UI.Gpu.UIRuntime.ApplyBundle(this, bundle);");
        sb.AppendLine();

        // 初始化命名元素引用
        foreach (var namedElement in document.NamedElements)
        {
            sb.AppendLine($"        this.{namedElement.Name} = ({namedElement.TypeName ?? "Jalium.UI.FrameworkElement"})this.FindName(\"{namedElement.Name}\")!;");
        }

        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetOutputPath(string inputFile, CompilerCliOptions options)
    {
        if (!string.IsNullOrEmpty(options.OutputFile))
        {
            return options.OutputFile;
        }

        var fileName = Path.GetFileNameWithoutExtension(inputFile);
        var outputDir = options.OutputDirectory ?? Path.GetDirectoryName(inputFile) ?? ".";

        return Path.Combine(outputDir, fileName + ".juib");
    }

    private static CompilerCliOptions ParseOptions(string[] args)
    {
        var options = new CompilerCliOptions();
        var i = 0;

        while (i < args.Length)
        {
            var arg = args[i];

            switch (arg)
            {
                case "-o":
                case "--output":
                    if (i + 1 < args.Length)
                    {
                        options.OutputFile = args[++i];
                    }
                    break;

                case "-d":
                case "--output-dir":
                    if (i + 1 < args.Length)
                    {
                        options.OutputDirectory = args[++i];
                    }
                    break;

                case "-O":
                case "--optimize":
                    options.Optimize = true;
                    break;

                case "-O0":
                    options.Optimize = false;
                    break;

                case "-g":
                case "--debug":
                    options.Debug = true;
                    break;

                case "-c":
                case "--codegen":
                    options.GenerateCodeBehind = true;
                    break;

                case "-n":
                case "--namespace":
                    if (i + 1 < args.Length)
                    {
                        options.RootNamespace = args[++i];
                    }
                    break;

                default:
                    if (!arg.StartsWith('-'))
                    {
                        options.InputFiles.Add(arg);
                    }
                    break;
            }

            i++;
        }

        return options;
    }

    private static void PrintHelp()
    {
        Console.WriteLine("""
            Jalium.UI JALXAML 编译器 (jalxamlc)

            用法: jalxamlc [选项] <input.jalxaml> [更多文件...]

            选项:
              -o, --output <path>    指定输出文件路径
              -d, --output-dir <dir> 指定输出目录
              -O, --optimize         启用优化（默认启用）
              -O0                    禁用优化
              -g, --debug            生成调试信息
              -c, --codegen          生成代码隐藏文件 (.g.cs)
              -n, --namespace <ns>   指定代码生成的根命名空间
              -h, --help             显示帮助信息
              -v, --version          显示版本信息

            示例:
              jalxamlc MainWindow.jalxaml
              jalxamlc -o bin/MainWindow.juib MainWindow.jalxaml
              jalxamlc -c -n MyApp MainWindow.jalxaml
              jalxamlc -d bin *.jalxaml
            """);
    }

    private static void PrintVersion()
    {
        Console.WriteLine("jalxamlc 1.0.0");
        Console.WriteLine("Jalium.UI JALXAML Compiler");
    }
}

internal class CompilerCliOptions
{
    public List<string> InputFiles { get; } = new();
    public string? OutputFile { get; set; }
    public string? OutputDirectory { get; set; }
    public bool Optimize { get; set; } = true;
    public bool Debug { get; set; }
    public bool GenerateCodeBehind { get; set; }
    public string? RootNamespace { get; set; }
}
