// <auto-generated-path>Editor/LanguageServer/Protocol/LspCodeAction.cs</auto-generated-path>
// LSP code action types.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Jalium.UI.Controls.Editor.LanguageServer.Protocol;

/// <summary>
/// Parameters for the textDocument/codeAction request.
/// </summary>
public sealed class CodeActionParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("range")]
    public LspRange Range { get; set; } = new();

    [JsonPropertyName("context")]
    public CodeActionContext Context { get; set; } = new();

    [JsonPropertyName("workDoneToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WorkDoneToken { get; set; }

    [JsonPropertyName("partialResultToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PartialResultToken { get; set; }
}

/// <summary>
/// Contains additional diagnostic information about the context in which a code action is run.
/// </summary>
public sealed class CodeActionContext
{
    [JsonPropertyName("diagnostics")]
    public List<Diagnostic> Diagnostics { get; set; } = [];

    [JsonPropertyName("only")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? Only { get; set; }

    [JsonPropertyName("triggerKind")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CodeActionTriggerKind? TriggerKind { get; set; }
}

/// <summary>
/// The reason why code actions were requested.
/// </summary>
public enum CodeActionTriggerKind
{
    Invoked = 1,
    Automatic = 2,
}

/// <summary>
/// A code action represents a change that can be performed in code.
/// </summary>
public sealed class CodeAction
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("kind")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Kind { get; set; }

    [JsonPropertyName("diagnostics")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<Diagnostic>? Diagnostics { get; set; }

    [JsonPropertyName("isPreferred")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsPreferred { get; set; }

    [JsonPropertyName("disabled")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CodeActionDisabled? Disabled { get; set; }

    [JsonPropertyName("edit")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public WorkspaceEdit? Edit { get; set; }

    [JsonPropertyName("command")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public LspCommand? Command { get; set; }

    [JsonPropertyName("data")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Data { get; set; }
}

/// <summary>
/// Marks a code action as disabled, providing a reason.
/// </summary>
public sealed class CodeActionDisabled
{
    [JsonPropertyName("reason")]
    public string Reason { get; set; } = string.Empty;
}

/// <summary>
/// Predefined code action kinds.
/// </summary>
public static class CodeActionKind
{
    public const string Empty = "";
    public const string QuickFix = "quickfix";
    public const string Refactor = "refactor";
    public const string RefactorExtract = "refactor.extract";
    public const string RefactorInline = "refactor.inline";
    public const string RefactorRewrite = "refactor.rewrite";
    public const string Source = "source";
    public const string SourceOrganizeImports = "source.organizeImports";
    public const string SourceFixAll = "source.fixAll";
}
