// <auto-generated-path>Editor/LanguageServer/Protocol/LspCodeLens.cs</auto-generated-path>
// LSP Code Lens types.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Jalium.UI.Controls.Editor.LanguageServer.Protocol;

/// <summary>
/// Parameters for a CodeLens request.
/// </summary>
public sealed class CodeLensParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("workDoneToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WorkDoneToken { get; set; }

    [JsonPropertyName("partialResultToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PartialResultToken { get; set; }
}

/// <summary>
/// A code lens represents a command that should be shown along with source text.
/// </summary>
public sealed class CodeLens
{
    [JsonPropertyName("range")]
    public LspRange Range { get; set; } = new();

    [JsonPropertyName("command")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public LspCommand? Command { get; set; }

    [JsonPropertyName("data")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Data { get; set; }
}
