// <auto-generated-path>Editor/LanguageServer/Protocol/LspCompletion.cs</auto-generated-path>
// LSP completion types — CompletionParams, CompletionItem, CompletionList, etc.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Jalium.UI.Controls.Editor.LanguageServer.Protocol;

/// <summary>
/// Parameters for the completion request.
/// </summary>
public sealed class CompletionParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("position")]
    public LspPosition Position { get; set; } = new();

    [JsonPropertyName("context")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CompletionContext? Context { get; set; }
}

/// <summary>
/// Contains additional information about the context in which a completion request is triggered.
/// </summary>
public sealed class CompletionContext
{
    [JsonPropertyName("triggerKind")]
    public CompletionTriggerKind TriggerKind { get; set; }

    [JsonPropertyName("triggerCharacter")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TriggerCharacter { get; set; }
}

/// <summary>
/// How a completion was triggered.
/// </summary>
public enum CompletionTriggerKind
{
    Invoked = 1,
    TriggerCharacter = 2,
    TriggerForIncompleteCompletions = 3,
}

/// <summary>
/// Represents a collection of completion items to be presented in the editor.
/// </summary>
public sealed class CompletionList
{
    [JsonPropertyName("isIncomplete")]
    public bool IsIncomplete { get; set; }

    [JsonPropertyName("itemDefaults")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CompletionItemDefaults? ItemDefaults { get; set; }

    [JsonPropertyName("items")]
    public CompletionItem[] Items { get; set; } = [];
}

/// <summary>
/// In many cases the items of an actual completion result share the same value for properties
/// like commitCharacters or the range of a text edit. A completion list can therefore define
/// item defaults which will be used if an individual completion item doesn't specify the value itself.
/// </summary>
public sealed class CompletionItemDefaults
{
    [JsonPropertyName("commitCharacters")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string[]? CommitCharacters { get; set; }

    [JsonPropertyName("editRange")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public LspRange? EditRange { get; set; }

    [JsonPropertyName("insertTextFormat")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public InsertTextFormat? InsertTextFormat { get; set; }

    [JsonPropertyName("insertTextMode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public InsertTextMode? InsertTextMode { get; set; }

    [JsonPropertyName("data")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Data { get; set; }
}

/// <summary>
/// A completion item represents a text snippet that is proposed to complete text that is being typed.
/// </summary>
public sealed class CompletionItem
{
    [JsonPropertyName("label")]
    public string Label { get; set; } = string.Empty;

    [JsonPropertyName("labelDetails")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CompletionItemLabelDetails? LabelDetails { get; set; }

    [JsonPropertyName("kind")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CompletionItemKind? Kind { get; set; }

    [JsonPropertyName("tags")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CompletionItemTag[]? Tags { get; set; }

    [JsonPropertyName("detail")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Detail { get; set; }

    [JsonPropertyName("documentation")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public MarkupContent? Documentation { get; set; }

    [JsonPropertyName("deprecated")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Deprecated { get; set; }

    [JsonPropertyName("preselect")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Preselect { get; set; }

    [JsonPropertyName("sortText")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SortText { get; set; }

    [JsonPropertyName("filterText")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? FilterText { get; set; }

    [JsonPropertyName("insertText")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? InsertText { get; set; }

    [JsonPropertyName("insertTextFormat")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public InsertTextFormat? InsertTextFormat { get; set; }

    [JsonPropertyName("insertTextMode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public InsertTextMode? InsertTextMode { get; set; }

    [JsonPropertyName("textEdit")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TextEdit? TextEdit { get; set; }

    [JsonPropertyName("textEditText")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TextEditText { get; set; }

    [JsonPropertyName("additionalTextEdits")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TextEdit[]? AdditionalTextEdits { get; set; }

    [JsonPropertyName("commitCharacters")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string[]? CommitCharacters { get; set; }

    [JsonPropertyName("command")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public LspCommand? Command { get; set; }

    [JsonPropertyName("data")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Data { get; set; }
}

/// <summary>
/// Additional details for a completion item label.
/// </summary>
public sealed class CompletionItemLabelDetails
{
    [JsonPropertyName("detail")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Detail { get; set; }

    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Description { get; set; }
}

/// <summary>
/// The kind of a completion entry.
/// </summary>
public enum CompletionItemKind
{
    Text = 1,
    Method = 2,
    Function = 3,
    Constructor = 4,
    Field = 5,
    Variable = 6,
    Class = 7,
    Interface = 8,
    Module = 9,
    Property = 10,
    Unit = 11,
    Value = 12,
    Enum = 13,
    Keyword = 14,
    Snippet = 15,
    Color = 16,
    File = 17,
    Reference = 18,
    Folder = 19,
    EnumMember = 20,
    Constant = 21,
    Struct = 22,
    Event = 23,
    Operator = 24,
    TypeParameter = 25,
}

/// <summary>
/// Completion item tags are extra annotations that tweak the rendering of a completion item.
/// </summary>
public enum CompletionItemTag
{
    Deprecated = 1,
}

/// <summary>
/// Defines whether the insert text in a completion item should be interpreted as plain text or a snippet.
/// </summary>
public enum InsertTextFormat
{
    PlainText = 1,
    Snippet = 2,
}

/// <summary>
/// How whitespace and indentation is handled during completion item insertion.
/// </summary>
public enum InsertTextMode
{
    AsIs = 1,
    AdjustIndentation = 2,
}
