// <auto-generated-path>Editor/LanguageServer/Protocol/LspDiagnostics.cs</auto-generated-path>
// LSP diagnostic types — Diagnostic, PublishDiagnosticsParams, DocumentDiagnosticReport, etc.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Jalium.UI.Controls.Editor.LanguageServer.Protocol;

/// <summary>
/// Diagnostic severity levels.
/// </summary>
public enum DiagnosticSeverity
{
    Error = 1,
    Warning = 2,
    Information = 3,
    Hint = 4,
}

/// <summary>
/// Represents a related message and source code location for a diagnostic.
/// </summary>
public sealed class DiagnosticRelatedInformation
{
    [JsonPropertyName("location")]
    public Location Location { get; set; } = new();

    [JsonPropertyName("message")]
    public string Message { get; set; } = string.Empty;
}

/// <summary>
/// Represents a diagnostic, such as a compiler error or warning.
/// </summary>
public sealed class Diagnostic
{
    [JsonPropertyName("range")]
    public LspRange Range { get; set; } = new();

    [JsonPropertyName("severity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DiagnosticSeverity? Severity { get; set; }

    [JsonPropertyName("code")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Code { get; set; }

    [JsonPropertyName("codeDescription")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CodeDescription? CodeDescription { get; set; }

    [JsonPropertyName("source")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Source { get; set; }

    [JsonPropertyName("message")]
    public string Message { get; set; } = string.Empty;

    [JsonPropertyName("tags")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DiagnosticTag[]? Tags { get; set; }

    [JsonPropertyName("relatedInformation")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DiagnosticRelatedInformation[]? RelatedInformation { get; set; }

    [JsonPropertyName("data")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Data { get; set; }
}

/// <summary>
/// Structure to capture a description for an error code.
/// </summary>
public sealed class CodeDescription
{
    [JsonPropertyName("href")]
    public string Href { get; set; } = string.Empty;
}

/// <summary>
/// Parameters for the publish diagnostics notification.
/// </summary>
public sealed class PublishDiagnosticsParams
{
    [JsonPropertyName("uri")]
    public string Uri { get; set; } = string.Empty;

    [JsonPropertyName("version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? Version { get; set; }

    [JsonPropertyName("diagnostics")]
    public Diagnostic[] Diagnostics { get; set; } = [];
}

/// <summary>
/// Parameters for the document diagnostic request.
/// </summary>
public sealed class DocumentDiagnosticParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("identifier")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Identifier { get; set; }

    [JsonPropertyName("previousResultId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? PreviousResultId { get; set; }
}

/// <summary>
/// A diagnostic report with a full set of problems.
/// </summary>
public sealed class FullDocumentDiagnosticReport
{
    [JsonPropertyName("kind")]
    public string Kind => "full";

    [JsonPropertyName("resultId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ResultId { get; set; }

    [JsonPropertyName("items")]
    public Diagnostic[] Items { get; set; } = [];
}

/// <summary>
/// A diagnostic report indicating that the last returned report is still accurate.
/// </summary>
public sealed class UnchangedDocumentDiagnosticReport
{
    [JsonPropertyName("kind")]
    public string Kind => "unchanged";

    [JsonPropertyName("resultId")]
    public string ResultId { get; set; } = string.Empty;
}

/// <summary>
/// Parameters for the workspace diagnostic request.
/// </summary>
public sealed class WorkspaceDiagnosticParams
{
    [JsonPropertyName("identifier")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Identifier { get; set; }

    [JsonPropertyName("previousResultIds")]
    public PreviousResultId[] PreviousResultIds { get; set; } = [];
}

/// <summary>
/// A previous result id in a workspace diagnostic request.
/// </summary>
public sealed class PreviousResultId
{
    [JsonPropertyName("uri")]
    public string Uri { get; set; } = string.Empty;

    [JsonPropertyName("value")]
    public string Value { get; set; } = string.Empty;
}

/// <summary>
/// A workspace diagnostic report.
/// </summary>
public sealed class WorkspaceDiagnosticReport
{
    [JsonPropertyName("items")]
    public WorkspaceDocumentDiagnosticReport[] Items { get; set; } = [];
}

/// <summary>
/// A diagnostic report for a workspace document.
/// </summary>
public sealed class WorkspaceDocumentDiagnosticReport
{
    [JsonPropertyName("uri")]
    public string Uri { get; set; } = string.Empty;

    [JsonPropertyName("version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? Version { get; set; }

    [JsonPropertyName("kind")]
    public string Kind { get; set; } = string.Empty;

    [JsonPropertyName("resultId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ResultId { get; set; }

    [JsonPropertyName("items")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Diagnostic[]? Items { get; set; }
}
