// <auto-generated-path>Editor/LanguageServer/Protocol/LspFormatting.cs</auto-generated-path>
// LSP Document Formatting request types.

using System.Text.Json.Serialization;

namespace Jalium.UI.Controls.Editor.LanguageServer.Protocol;

/// <summary>
/// Parameters for a DocumentFormatting request.
/// </summary>
public sealed class DocumentFormattingParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("options")]
    public FormattingOptions Options { get; set; } = new();
}

/// <summary>
/// Parameters for a DocumentRangeFormatting request.
/// </summary>
public sealed class DocumentRangeFormattingParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("range")]
    public LspRange Range { get; set; } = new();

    [JsonPropertyName("options")]
    public FormattingOptions Options { get; set; } = new();
}

/// <summary>
/// Parameters for a DocumentOnTypeFormatting request.
/// </summary>
public sealed class DocumentOnTypeFormattingParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("position")]
    public LspPosition Position { get; set; } = new();

    [JsonPropertyName("ch")]
    public string Ch { get; set; } = string.Empty;

    [JsonPropertyName("options")]
    public FormattingOptions Options { get; set; } = new();
}

/// <summary>
/// Value object describing what options formatting should use.
/// </summary>
public sealed class FormattingOptions
{
    [JsonPropertyName("tabSize")]
    public int TabSize { get; set; }

    [JsonPropertyName("insertSpaces")]
    public bool InsertSpaces { get; set; }

    [JsonPropertyName("trimTrailingWhitespace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? TrimTrailingWhitespace { get; set; }

    [JsonPropertyName("insertFinalNewline")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? InsertFinalNewline { get; set; }

    [JsonPropertyName("trimFinalNewlines")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? TrimFinalNewlines { get; set; }
}
