// <auto-generated-path>Editor/LanguageServer/Protocol/LspInlineValue.cs</auto-generated-path>
// LSP Inline Value types — textDocument/inlineValue.

using System.Text.Json.Serialization;

namespace Jalium.UI.Controls.Editor.LanguageServer.Protocol;

/// <summary>
/// Parameters for the textDocument/inlineValue request.
/// </summary>
public sealed class InlineValueParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("range")]
    public LspRange Range { get; set; } = new();

    [JsonPropertyName("context")]
    public InlineValueContext Context { get; set; } = new();

    [JsonPropertyName("workDoneToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WorkDoneToken { get; set; }
}

/// <summary>
/// Additional information about the context in which inline values are requested.
/// </summary>
public sealed class InlineValueContext
{
    [JsonPropertyName("frameId")]
    public int FrameId { get; set; }

    [JsonPropertyName("stoppedLocation")]
    public LspRange StoppedLocation { get; set; } = new();
}

/// <summary>
/// An inline value that displays literal text.
/// </summary>
public sealed class InlineValueText
{
    [JsonPropertyName("range")]
    public LspRange Range { get; set; } = new();

    [JsonPropertyName("text")]
    public string Text { get; set; } = string.Empty;
}

/// <summary>
/// An inline value that looks up a variable by name at the stopped location.
/// </summary>
public sealed class InlineValueVariableLookup
{
    [JsonPropertyName("range")]
    public LspRange Range { get; set; } = new();

    [JsonPropertyName("variableName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? VariableName { get; set; }

    [JsonPropertyName("caseSensitiveLookup")]
    public bool CaseSensitiveLookup { get; set; }
}

/// <summary>
/// An inline value determined by an evaluatable expression at the stopped location.
/// </summary>
public sealed class InlineValueEvaluatableExpression
{
    [JsonPropertyName("range")]
    public LspRange Range { get; set; } = new();

    [JsonPropertyName("expression")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Expression { get; set; }
}
