// <auto-generated-path>Editor/LanguageServer/Protocol/LspLinkedEditing.cs</auto-generated-path>
// LSP Linked Editing Range types — textDocument/linkedEditingRange.

using System.Text.Json.Serialization;

namespace Jalium.UI.Controls.Editor.LanguageServer.Protocol;

/// <summary>
/// Parameters for the textDocument/linkedEditingRange request.
/// </summary>
public sealed class LinkedEditingRangeParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("position")]
    public LspPosition Position { get; set; } = new();

    [JsonPropertyName("workDoneToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WorkDoneToken { get; set; }
}

/// <summary>
/// The result of a linked editing range request.
/// </summary>
public sealed class LinkedEditingRanges
{
    [JsonPropertyName("ranges")]
    public LspRange[] Ranges { get; set; } = [];

    [JsonPropertyName("wordPattern")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? WordPattern { get; set; }
}
