// <auto-generated-path>Editor/LanguageServer/Protocol/LspMessages.cs</auto-generated-path>
// JSON-RPC 2.0 message types for LSP.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Jalium.UI.Controls.Editor.LanguageServer.Protocol;

/// <summary>
/// A JSON-RPC 2.0 request message.
/// </summary>
public sealed class RequestMessage
{
    [JsonPropertyName("jsonrpc")]
    public string JsonRpc { get; set; } = "2.0";

    [JsonPropertyName("id")]
    public object Id { get; set; } = 0;

    [JsonPropertyName("method")]
    public string Method { get; set; } = string.Empty;

    [JsonPropertyName("params")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Params { get; set; }
}

/// <summary>
/// A JSON-RPC 2.0 response message.
/// </summary>
public sealed class ResponseMessage
{
    [JsonPropertyName("jsonrpc")]
    public string JsonRpc { get; set; } = "2.0";

    [JsonPropertyName("id")]
    public object? Id { get; set; }

    [JsonPropertyName("result")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Result { get; set; }

    [JsonPropertyName("error")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ResponseError? Error { get; set; }
}

/// <summary>
/// A JSON-RPC 2.0 notification message (no id).
/// </summary>
public sealed class NotificationMessage
{
    [JsonPropertyName("jsonrpc")]
    public string JsonRpc { get; set; } = "2.0";

    [JsonPropertyName("method")]
    public string Method { get; set; } = string.Empty;

    [JsonPropertyName("params")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Params { get; set; }
}

/// <summary>
/// An error object in a JSON-RPC 2.0 response.
/// </summary>
public sealed class ResponseError
{
    [JsonPropertyName("code")]
    public int Code { get; set; }

    [JsonPropertyName("message")]
    public string Message { get; set; } = string.Empty;

    [JsonPropertyName("data")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Data { get; set; }
}

/// <summary>
/// LSP error codes.
/// </summary>
public static class LspErrorCodes
{
    public const int ParseError = -32700;
    public const int InvalidRequest = -32600;
    public const int MethodNotFound = -32601;
    public const int InvalidParams = -32602;
    public const int InternalError = -32603;

    // LSP-specific
    public const int ServerNotInitialized = -32002;
    public const int UnknownErrorCode = -32001;
    public const int RequestFailed = -32803;
    public const int ServerCancelled = -32802;
    public const int ContentModified = -32801;
    public const int RequestCancelled = -32800;
}

/// <summary>
/// LSP method names.
/// </summary>
public static class LspMethods
{
    // Lifecycle
    public const string Initialize = "initialize";
    public const string Initialized = "initialized";
    public const string Shutdown = "shutdown";
    public const string Exit = "exit";

    // Text Synchronization
    public const string TextDocumentDidOpen = "textDocument/didOpen";
    public const string TextDocumentDidChange = "textDocument/didChange";
    public const string TextDocumentDidSave = "textDocument/didSave";
    public const string TextDocumentDidClose = "textDocument/didClose";
    public const string TextDocumentWillSave = "textDocument/willSave";
    public const string TextDocumentWillSaveWaitUntil = "textDocument/willSaveWaitUntil";

    // Diagnostics
    public const string TextDocumentPublishDiagnostics = "textDocument/publishDiagnostics";
    public const string TextDocumentDiagnostic = "textDocument/diagnostic";
    public const string WorkspaceDiagnostic = "workspace/diagnostic";

    // Completion
    public const string TextDocumentCompletion = "textDocument/completion";
    public const string CompletionItemResolve = "completionItem/resolve";

    // Hover & Signature
    public const string TextDocumentHover = "textDocument/hover";
    public const string TextDocumentSignatureHelp = "textDocument/signatureHelp";

    // Navigation
    public const string TextDocumentDeclaration = "textDocument/declaration";
    public const string TextDocumentDefinition = "textDocument/definition";
    public const string TextDocumentTypeDefinition = "textDocument/typeDefinition";
    public const string TextDocumentImplementation = "textDocument/implementation";
    public const string TextDocumentReferences = "textDocument/references";

    // Highlight & Selection
    public const string TextDocumentDocumentHighlight = "textDocument/documentHighlight";
    public const string TextDocumentSelectionRange = "textDocument/selectionRange";

    // Symbols
    public const string TextDocumentDocumentSymbol = "textDocument/documentSymbol";
    public const string WorkspaceSymbol = "workspace/symbol";
    public const string WorkspaceSymbolResolve = "workspaceSymbol/resolve";

    // Code Action & Command
    public const string TextDocumentCodeAction = "textDocument/codeAction";
    public const string CodeActionResolve = "codeAction/resolve";
    public const string WorkspaceExecuteCommand = "workspace/executeCommand";
    public const string WorkspaceApplyEdit = "workspace/applyEdit";

    // CodeLens
    public const string TextDocumentCodeLens = "textDocument/codeLens";
    public const string CodeLensResolve = "codeLens/resolve";

    // Document Link
    public const string TextDocumentDocumentLink = "textDocument/documentLink";
    public const string DocumentLinkResolve = "documentLink/resolve";

    // Color
    public const string TextDocumentDocumentColor = "textDocument/documentColor";
    public const string TextDocumentColorPresentation = "textDocument/colorPresentation";

    // Formatting
    public const string TextDocumentFormatting = "textDocument/formatting";
    public const string TextDocumentRangeFormatting = "textDocument/rangeFormatting";
    public const string TextDocumentOnTypeFormatting = "textDocument/onTypeFormatting";

    // Rename
    public const string TextDocumentRename = "textDocument/rename";
    public const string TextDocumentPrepareRename = "textDocument/prepareRename";

    // Folding & Structure
    public const string TextDocumentFoldingRange = "textDocument/foldingRange";
    public const string TextDocumentLinkedEditingRange = "textDocument/linkedEditingRange";

    // Semantic Tokens
    public const string TextDocumentSemanticTokensFull = "textDocument/semanticTokens/full";
    public const string TextDocumentSemanticTokensFullDelta = "textDocument/semanticTokens/full/delta";
    public const string TextDocumentSemanticTokensRange = "textDocument/semanticTokens/range";

    // Inlay Hints
    public const string TextDocumentInlayHint = "textDocument/inlayHint";
    public const string InlayHintResolve = "inlayHint/resolve";

    // Inline Values
    public const string TextDocumentInlineValue = "textDocument/inlineValue";

    // Moniker
    public const string TextDocumentMoniker = "textDocument/moniker";

    // Call Hierarchy
    public const string TextDocumentPrepareCallHierarchy = "textDocument/prepareCallHierarchy";
    public const string CallHierarchyIncomingCalls = "callHierarchy/incomingCalls";
    public const string CallHierarchyOutgoingCalls = "callHierarchy/outgoingCalls";

    // Type Hierarchy
    public const string TextDocumentPrepareTypeHierarchy = "textDocument/prepareTypeHierarchy";
    public const string TypeHierarchySupertypes = "typeHierarchy/supertypes";
    public const string TypeHierarchySubtypes = "typeHierarchy/subtypes";

    // Workspace
    public const string WorkspaceDidChangeWatchedFiles = "workspace/didChangeWatchedFiles";
    public const string WorkspaceDidChangeConfiguration = "workspace/didChangeConfiguration";
    public const string WorkspaceDidChangeWorkspaceFolders = "workspace/didChangeWorkspaceFolders";
    public const string WorkspaceWillCreateFiles = "workspace/willCreateFiles";
    public const string WorkspaceDidCreateFiles = "workspace/didCreateFiles";
    public const string WorkspaceWillRenameFiles = "workspace/willRenameFiles";
    public const string WorkspaceDidRenameFiles = "workspace/didRenameFiles";
    public const string WorkspaceWillDeleteFiles = "workspace/willDeleteFiles";
    public const string WorkspaceDidDeleteFiles = "workspace/didDeleteFiles";
    public const string WorkspaceConfiguration = "workspace/configuration";

    // Window
    public const string WindowShowMessage = "window/showMessage";
    public const string WindowShowMessageRequest = "window/showMessageRequest";
    public const string WindowLogMessage = "window/logMessage";
    public const string WindowShowDocument = "window/showDocument";
    public const string WindowWorkDoneProgressCreate = "window/workDoneProgress/create";
    public const string Progress = "$/progress";

    // Notebook
    public const string NotebookDocumentDidOpen = "notebookDocument/didOpen";
    public const string NotebookDocumentDidChange = "notebookDocument/didChange";
    public const string NotebookDocumentDidSave = "notebookDocument/didSave";
    public const string NotebookDocumentDidClose = "notebookDocument/didClose";

    // Cancellation
    public const string CancelRequest = "$/cancelRequest";
}
