// <auto-generated-path>Editor/LanguageServer/Protocol/LspMoniker.cs</auto-generated-path>
// LSP Moniker types — textDocument/moniker.

using System.Text.Json.Serialization;

namespace Jalium.UI.Controls.Editor.LanguageServer.Protocol;

/// <summary>
/// Parameters for the textDocument/moniker request.
/// </summary>
public sealed class MonikerParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("position")]
    public LspPosition Position { get; set; } = new();

    [JsonPropertyName("workDoneToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WorkDoneToken { get; set; }

    [JsonPropertyName("partialResultToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PartialResultToken { get; set; }
}

/// <summary>
/// Moniker definition to match LSIF specification.
/// </summary>
public sealed class Moniker
{
    [JsonPropertyName("scheme")]
    public string Scheme { get; set; } = string.Empty;

    [JsonPropertyName("identifier")]
    public string Identifier { get; set; } = string.Empty;

    [JsonPropertyName("unique")]
    public string Unique { get; set; } = UniquenessLevel.Document;

    [JsonPropertyName("kind")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Kind { get; set; }
}

/// <summary>
/// The uniqueness level of a moniker.
/// </summary>
public static class UniquenessLevel
{
    public const string Document = "document";
    public const string Project = "project";
    public const string Group = "group";
    public const string Scheme = "scheme";
    public const string Global = "global";
}

/// <summary>
/// The moniker kind.
/// </summary>
public static class MonikerKind
{
    public const string Import = "import";
    public const string Export = "export";
    public const string Local = "local";
}
