// <auto-generated-path>Editor/LanguageServer/Protocol/LspNavigation.cs</auto-generated-path>
// LSP Navigation request types — Declaration, Definition, TypeDefinition, Implementation, References.

using System.Text.Json.Serialization;

namespace Jalium.UI.Controls.Editor.LanguageServer.Protocol;

/// <summary>
/// Parameters for a Declaration request.
/// </summary>
public sealed class DeclarationParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("position")]
    public LspPosition Position { get; set; } = new();

    [JsonPropertyName("workDoneToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WorkDoneToken { get; set; }

    [JsonPropertyName("partialResultToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PartialResultToken { get; set; }
}

/// <summary>
/// Parameters for a Definition request.
/// </summary>
public sealed class DefinitionParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("position")]
    public LspPosition Position { get; set; } = new();

    [JsonPropertyName("workDoneToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WorkDoneToken { get; set; }

    [JsonPropertyName("partialResultToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PartialResultToken { get; set; }
}

/// <summary>
/// Parameters for a Type Definition request.
/// </summary>
public sealed class TypeDefinitionParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("position")]
    public LspPosition Position { get; set; } = new();

    [JsonPropertyName("workDoneToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WorkDoneToken { get; set; }

    [JsonPropertyName("partialResultToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PartialResultToken { get; set; }
}

/// <summary>
/// Parameters for an Implementation request.
/// </summary>
public sealed class ImplementationParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("position")]
    public LspPosition Position { get; set; } = new();

    [JsonPropertyName("workDoneToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WorkDoneToken { get; set; }

    [JsonPropertyName("partialResultToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PartialResultToken { get; set; }
}

/// <summary>
/// Parameters for a References request.
/// </summary>
public sealed class ReferenceParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; } = new();

    [JsonPropertyName("position")]
    public LspPosition Position { get; set; } = new();

    [JsonPropertyName("context")]
    public ReferenceContext Context { get; set; } = new();

    [JsonPropertyName("workDoneToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? WorkDoneToken { get; set; }

    [JsonPropertyName("partialResultToken")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? PartialResultToken { get; set; }
}

/// <summary>
/// Context for a References request.
/// </summary>
public sealed class ReferenceContext
{
    [JsonPropertyName("includeDeclaration")]
    public bool IncludeDeclaration { get; set; }
}
