// <auto-generated-path>Editor/LanguageServer/JsonRpc/JsonRpcException.cs</auto-generated-path>
// Exception type for JSON-RPC error responses.

namespace Jalium.UI.Controls.Editor.LanguageServer.JsonRpc;

/// <summary>
/// Exception thrown when a JSON-RPC request returns an error response.
/// </summary>
public sealed class JsonRpcException : Exception
{
    /// <summary>The JSON-RPC error code.</summary>
    public int Code { get; }

    /// <summary>Optional structured error data from the server.</summary>
    public object? Data { get; }

    public JsonRpcException(int code, string message, object? data = null)
        : base(message)
    {
        Code = code;
        Data = data;
    }
}
