@echo off
REM Compile core D3D12 shaders to .cso bytecode and generate d3d12_shader_bytecode.h
setlocal enabledelayedexpansion

set "FXC=%ProgramFiles(x86)%\Windows Kits\10\bin\10.0.26100.0\x64\fxc.exe"
set OUTDIR=compiled
if not exist %OUTDIR% mkdir %OUTDIR%

set ERRORS=0

REM ── Vertex shaders (vs_5_1) ──
for %%f in (sdf_rect.vs bitmap_text.vs bitmap_quad.vs custom_effect.vs triangle.vs) do (
    echo Compiling %%f.hlsl ...
    "%FXC%" /nologo /T vs_5_1 /O3 /E main /Fo %OUTDIR%\%%f.cso %%f.hlsl
    if errorlevel 1 (
        echo ERROR: %%f.hlsl failed to compile
        set /a ERRORS+=1
    )
)

REM ── Pixel shaders (ps_5_1) ──
for %%f in (sdf_rect.ps bitmap_text.ps bitmap_quad.ps triangle.ps) do (
    echo Compiling %%f.hlsl ...
    "%FXC%" /nologo /T ps_5_1 /O3 /E main /Fo %OUTDIR%\%%f.cso %%f.hlsl
    if errorlevel 1 (
        echo ERROR: %%f.hlsl failed to compile
        set /a ERRORS+=1
    )
)

if %ERRORS% neq 0 (
    echo.
    echo %ERRORS% shader(s) failed to compile.
    exit /b 1
)

echo.
echo All core shaders compiled successfully.
echo Generating d3d12_shader_bytecode.h ...

REM ── Generate C++ header with embedded bytecode ──
set "HDR=..\include\d3d12_shader_bytecode.h"

(
echo #pragma once
echo // Auto-generated pre-compiled core shader bytecode.
echo // Generated by compile_core_shaders.cmd — do not edit manually.
echo // Eliminates runtime D3DCompile for core rendering shaders.
echo.
echo namespace shader_bytecode {
) > "%HDR%"

for %%f in (sdf_rect.vs sdf_rect.ps bitmap_text.vs bitmap_text.ps bitmap_quad.vs bitmap_quad.ps custom_effect.vs triangle.vs triangle.ps) do (
    call :emit_array %%f
)

echo.>> "%HDR%"
echo } // namespace shader_bytecode>> "%HDR%"

echo Done: %HDR%
exit /b 0

:emit_array
set "NAME=%1"
set "CSOFILE=%OUTDIR%\%NAME%.cso"

REM Get file size
for %%A in (%CSOFILE%) do set FSIZE=%%~zA

REM Convert name to C++ identifier (dots to underscores, prefix with k)
set "VARNAME=%NAME:.=_%"

echo.>> "%HDR%"
echo static const unsigned int k%VARNAME%Size = %FSIZE%;>> "%HDR%"
echo static const unsigned char k%VARNAME%[] = {>> "%HDR%"

powershell -NoProfile -Command ^
    "$bytes = [System.IO.File]::ReadAllBytes('%CSOFILE%'); " ^
    "$sb = [System.Text.StringBuilder]::new(); " ^
    "for ($i = 0; $i -lt $bytes.Length; $i++) { " ^
    "    if ($i %% 16 -eq 0) { [void]$sb.Append('    '); } " ^
    "    [void]$sb.Append(('0x{0:x2}' -f $bytes[$i])); " ^
    "    if ($i -lt $bytes.Length - 1) { [void]$sb.Append(', '); } " ^
    "    if (($i + 1) %% 16 -eq 0) { [void]$sb.AppendLine(); } " ^
    "} " ^
    "Write-Host $sb.ToString() -NoNewline" >> "%HDR%"

echo.>> "%HDR%"
echo };>> "%HDR%"
goto :eof
