param(
    [string]$OutDir = (Join-Path $PSScriptRoot 'compiled'),
    [string]$HeaderPath = (Join-Path $PSScriptRoot '..\include\d3d12_shader_bytecode.h')
)

$shaders = @(
    'sdf_rect.vs', 'sdf_rect.ps',
    'bitmap_text.vs', 'bitmap_text.ps',
    'bitmap_quad.vs', 'bitmap_quad.ps',
    'custom_effect.vs',
    'triangle.vs', 'triangle.ps',
    'gaussian_blur.cs'
)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('// Auto-generated pre-compiled core shader bytecode.')
[void]$sb.AppendLine('// Generated by gen_bytecode_header.ps1 - do not edit manually.')
[void]$sb.AppendLine('// Eliminates runtime D3DCompile for core rendering shaders.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace shader_bytecode {')

foreach ($name in $shaders) {
    $csoFile = Join-Path $OutDir "$name.cso"
    if (-not (Test-Path $csoFile)) {
        Write-Warning "Missing: $csoFile - skipping"
        continue
    }
    $bytes = [System.IO.File]::ReadAllBytes($csoFile)
    $varName = 'k' + ($name -replace '\.', '_')

    [void]$sb.AppendLine()
    [void]$sb.AppendLine("static const unsigned int ${varName}Size = $($bytes.Length);")
    [void]$sb.AppendLine("static const unsigned char ${varName}[] = {")

    for ($i = 0; $i -lt $bytes.Length; $i++) {
        if ($i % 16 -eq 0) { [void]$sb.Append('    ') }
        [void]$sb.Append(('0x{0:x2}' -f $bytes[$i]))
        if ($i -lt $bytes.Length - 1) { [void]$sb.Append(', ') }
        if (($i + 1) % 16 -eq 0) { [void]$sb.AppendLine() }
    }
    if ($bytes.Length % 16 -ne 0) { [void]$sb.AppendLine() }
    [void]$sb.AppendLine('};')
}

[void]$sb.AppendLine()
[void]$sb.AppendLine('} // namespace shader_bytecode')

[System.IO.File]::WriteAllText($HeaderPath, $sb.ToString())
Write-Host "Generated $HeaderPath ($([System.IO.FileInfo]::new($HeaderPath).Length) bytes)"
